name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 6'

  workflow_dispatch:

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: 'macos'
            image: 'macos-14'
          - name: 'linux'
            image: 'ubuntu-24.04'
          - name: 'windows'
            image: 'windows-2022'

    name: main.${{ matrix.config.name }}
    runs-on: ${{ matrix.config.image }}

    # noinspection SpellCheckingInspection
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: NuGet cache
        uses: actions/cache@v3
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}.nuget.${{ hashFiles('**/*.fsproj') }}

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'Technetium.Frontend/package-lock.json'

      - name: Install the frontend dependencies
        working-directory: Technetium.Frontend
        run: npm ci

      - name: Build
        run: dotnet build

      - name: Test backend
        run: dotnet test

      - name: Test frontend
        working-directory: Technetium.Frontend
        run: npm test
